---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 8.3.0
  - name: ansible.utils
    version: 3.1.0
  - name: ansible.netcommon
    version: 6.0.0
  - name: ansible.windows
    version: 2.2.0
  - name: community.windows
    version: 2.1.0
  - name: zabbix.zabbix
    version: 1.3.6
  - name: community.zabbix
    version: 2.3.1